"""Where evidence clip videos are kept — behind one small interface (docs/EVIDENCE-CLIPS.md).

* `LocalEvidenceStorage` — a directory on the API's machine. Development and tests only: Render's disk
  is wiped on every deploy, so a production API refuses to start with it (`Settings`).
* `SupabaseEvidenceStorage` — a **private** Supabase Storage bucket, reached by the API alone with the
  service-role key. No app ever receives a storage URL, a signed URL or a credential: administrators
  watch a clip through the API, which checks who is asking and the clip's hash first.

Object keys are generated by `new_key()` from 256 random bits — never from ids, names or anything a
client sent — and every backend refuses a key of any other shape, so a path can never escape the
bucket or the directory. Errors never include the key, a URL or a credential.
"""

import os
import re
import secrets
import urllib.error
import urllib.request
from pathlib import Path
from typing import Protocol

from app.core.config import Settings

#: `clips/<43 url-safe base64 chars>.webm` — the only shape a key may have.
_KEY = re.compile(r"^clips/[A-Za-z0-9_-]{43}\.webm$")


class StorageError(Exception):
    """The storage backend could not complete an operation. Carries no key, URL or credential."""


class ObjectMissing(StorageError):
    """The object does not exist (deleted out of band, or never written)."""


def new_key() -> str:
    return f"clips/{secrets.token_urlsafe(32)}.webm"


def check_key(key: str) -> str:
    if not _KEY.fullmatch(key):
        raise StorageError("refused an object key of an unexpected shape")
    return key


class EvidenceStorage(Protocol):
    name: str

    def put(self, key: str, data: bytes, content_type: str) -> None: ...

    def get(self, key: str) -> bytes: ...

    def delete(self, key: str) -> None: ...


class LocalEvidenceStorage:
    """Files under one directory, written atomically, readable by this process only (where supported)."""

    name = "local"

    def __init__(self, root: str | Path) -> None:
        self.root = Path(root).resolve()

    def _path(self, key: str) -> Path:
        path = (self.root / check_key(key)).resolve()
        if self.root not in path.parents:
            raise StorageError("refused a path outside the evidence directory")
        return path

    def put(self, key: str, data: bytes, content_type: str) -> None:
        path = self._path(key)
        try:
            path.parent.mkdir(parents=True, exist_ok=True)
            if path.exists():
                raise StorageError("refused to overwrite an existing object")
            temporary = path.with_suffix(".partial")
            with open(temporary, "wb") as handle:
                handle.write(data)
            os.chmod(temporary, 0o600)
            os.replace(temporary, path)
        except OSError as error:
            raise StorageError(f"local write failed ({type(error).__name__})") from None

    def get(self, key: str) -> bytes:
        path = self._path(key)
        try:
            return path.read_bytes()
        except FileNotFoundError:
            raise ObjectMissing("object not found") from None
        except OSError as error:
            raise StorageError(f"local read failed ({type(error).__name__})") from None

    def delete(self, key: str) -> None:
        try:
            self._path(key).unlink(missing_ok=True)
        except OSError as error:
            raise StorageError(f"local delete failed ({type(error).__name__})") from None


class Transport(Protocol):
    def __call__(
        self, method: str, url: str, headers: dict[str, str], body: bytes | None, timeout: float
    ) -> tuple[int, bytes]: ...


def _urllib_transport(
    method: str, url: str, headers: dict[str, str], body: bytes | None, timeout: float
) -> tuple[int, bytes]:
    request = urllib.request.Request(url, data=body, method=method, headers=headers)  # noqa: S310 — https only
    try:
        with urllib.request.urlopen(request, timeout=timeout) as response:  # noqa: S310
            return response.status, response.read()
    except urllib.error.HTTPError as error:
        return error.code, b""
    except (urllib.error.URLError, TimeoutError, OSError) as error:
        raise StorageError(f"storage unreachable ({type(error).__name__})") from None


class SupabaseEvidenceStorage:
    """A private Supabase Storage bucket, via its REST API (no SDK). The bucket must be created PRIVATE
    by an operator (docs/EVIDENCE-CLIPS.md); this class never creates buckets or changes policies."""

    name = "supabase"

    def __init__(self, url: str, service_role_key: str, bucket: str, transport: Transport | None = None):
        if not url.startswith("https://"):
            raise StorageError("Supabase storage needs an https:// URL")
        self._base = url.rstrip("/") + "/storage/v1/object"
        self._key = service_role_key
        self._bucket = bucket
        self._send = transport or _urllib_transport

    def _headers(self, extra: dict[str, str] | None = None) -> dict[str, str]:
        return {"Authorization": f"Bearer {self._key}", "apikey": self._key, **(extra or {})}

    def put(self, key: str, data: bytes, content_type: str) -> None:
        url = f"{self._base}/{self._bucket}/{check_key(key)}"
        status, _ = self._send(
            "POST", url, self._headers({"Content-Type": content_type, "x-upsert": "false"}), data, 30.0
        )
        if status not in (200, 201):
            raise StorageError(f"storage upload refused (HTTP {status})")

    def get(self, key: str) -> bytes:
        url = f"{self._base}/authenticated/{self._bucket}/{check_key(key)}"
        status, body = self._send("GET", url, self._headers(), None, 30.0)
        if status in (400, 404):
            raise ObjectMissing("object not found")
        if status != 200:
            raise StorageError(f"storage download refused (HTTP {status})")
        return body

    def delete(self, key: str) -> None:
        url = f"{self._base}/{self._bucket}/{check_key(key)}"
        status, _ = self._send("DELETE", url, self._headers(), None, 30.0)
        if status not in (200, 204, 404):
            raise StorageError(f"storage delete refused (HTTP {status})")


_override: EvidenceStorage | None = None


def get_storage(settings: Settings) -> EvidenceStorage:
    """The configured backend. Tests may install their own with `use_storage`."""
    if _override is not None:
        return _override
    if settings.evidence_storage_backend == "supabase":
        if not (settings.supabase_url and settings.supabase_service_role_key):
            raise StorageError("Supabase storage is not configured")
        return SupabaseEvidenceStorage(
            settings.supabase_url,
            settings.supabase_service_role_key.get_secret_value(),
            settings.evidence_bucket,
        )
    return LocalEvidenceStorage(settings.evidence_local_dir)


def use_storage(storage: EvidenceStorage | None) -> None:
    global _override
    _override = storage
