"""Phase 6C — the vocabulary and the transitions of a human review. One place, tested for wording.

**The outcome is human-authored and never computed.** Nothing in this package reads a risk score to
choose, suggest, require or forbid an outcome: a HIGH-risk attempt may be CLEARED and a NORMAL one
FLAGGED. The risk (6A) and evidence (6B) are signals a reviewer reads; the decision is theirs.
(Detect → Correlate → Explain → Evidence → **Human Review → Administrative Decision**.)
"""

from app.models.review import ReviewOutcome, ReviewStatus

#: What each outcome records. Administrative language — no verdict about the candidate's intent.
OUTCOME_DESCRIPTIONS: dict[ReviewOutcome, str] = {
    ReviewOutcome.NO_ACTION: "Reviewed. Nothing requires administrative action.",
    ReviewOutcome.CLEARED: "Reviewed. The observations were examined and are not a concern for this attempt.",
    ReviewOutcome.FLAGGED: "Reviewed. The observations need further administrative follow-up.",
    ReviewOutcome.INVALIDATED: (
        "Reviewed. The administrator records that this attempt should not stand. Recorded only — "
        "the attempt, its score and what the candidate sees are not changed."
    ),
}

INTERPRETATION = (
    "This review is written by an administrator. The risk level and the evidence are generated by "
    "the system from observed events; they are signals for review and do not determine the outcome. "
    "An outcome may differ from the risk level."
)

#: The only transitions. `None` is an attempt with no review yet (reported as UNREVIEWED).
START_FROM: frozenset[ReviewStatus | None] = frozenset({None})
COMPLETE_FROM = frozenset({ReviewStatus.IN_REVIEW})
REVISE_FROM = frozenset({ReviewStatus.REVIEWED})
MARK_FROM = frozenset({ReviewStatus.IN_REVIEW})
NOTE_FROM = frozenset({ReviewStatus.IN_REVIEW, ReviewStatus.REVIEWED})

MAX_TEXT = 4000
