/**
 * The human review of one attempt (Phase 6C) — `backend/app/schemas/review.py`.
 *
 * Two kinds of information are kept apart on purpose. The **risk** and **evidence** are generated by
 * the system (6A/6B) and are signals; the **status, notes, marks and outcome** are written by an
 * administrator. The app never derives an outcome from a risk level, and every identity and
 * timestamp here comes from the server.
 */

import type { RiskLevel } from '../risk/types'

export type ReviewStatus = 'UNREVIEWED' | 'IN_REVIEW' | 'REVIEWED'
export type ReviewOutcome = 'NO_ACTION' | 'CLEARED' | 'FLAGGED' | 'INVALIDATED'
export type EvidenceMark = 'CONFIRMED' | 'DISMISSED'

export interface Person {
  id: string
  name: string
}

export interface ReviewContext {
  attemptId: string
  attemptNumber: number
  attemptStatus: string
  startedAt: string
  finalizedAt: string | null
  assessmentId: string
  assessmentTitle: string
  candidateName: string
  candidateRollNumber: string | null
}

export interface ReviewNote {
  noteId: string
  author: Person
  body: string
  createdAt: string
}

/** The system-generated summary recorded with a decision — what the reviewer saw, not an input to it. */
export interface DecisionBasis {
  policyVersion: string
  evidenceVersion: string
  asOf: string
  riskScore: number
  riskLevel: RiskLevel
  peakScore: number
  peakLevel: RiskLevel
  signalCount: number
  evidenceCount: number
  episodeCount: number
}

export interface ReviewDecision {
  revision: number
  outcome: ReviewOutcome
  outcomeDescription: string
  rationale: string
  decidedBy: Person
  decidedAt: string
  basis: DecisionBasis
}

export interface ReviewMark {
  evidenceId: string
  mark: EvidenceMark
  markedBy: Person
  markedAt: string
}

export interface ReviewHistoryEntry {
  action: string
  actor: Person
  occurredAt: string
  details: Record<string, unknown>
}

export interface AttemptReview {
  context: ReviewContext
  status: ReviewStatus
  version: number | null
  outcome: ReviewOutcome | null
  startedBy: Person | null
  startedAt: string | null
  completedBy: Person | null
  completedAt: string | null
  canComplete: boolean
  notes: ReviewNote[]
  /** Newest revision first; the first is the current outcome. */
  decisions: ReviewDecision[]
  marks: ReviewMark[]
  history: ReviewHistoryEntry[]
  outcomeOptions: { outcome: ReviewOutcome; description: string }[]
  interpretation: string
}

export interface QueueItem {
  attemptId: string
  attemptNumber: number
  attemptStatus: string
  startedAt: string
  finalizedAt: string | null
  assessmentId: string
  assessmentTitle: string
  candidateName: string
  candidateRollNumber: string | null
  riskLevel: RiskLevel
  riskScore: number
  peakLevel: RiskLevel
  reviewStatus: ReviewStatus
  outcome: ReviewOutcome | null
  reviewedBy: Person | null
  reviewedAt: string | null
}

export interface ReviewQueue {
  counts: Record<ReviewStatus, number>
  items: QueueItem[]
  nextCursor: string | null
  interpretation: string
}

type Raw = Record<string, unknown>

const person = (raw: unknown): Person | null => {
  const p = raw as Raw | null
  return p ? { id: p.id as string, name: p.name as string } : null
}

export function toReview(raw: Raw): AttemptReview {
  const c = raw.context as Raw
  return {
    context: {
      attemptId: c.attempt_id as string,
      attemptNumber: c.attempt_number as number,
      attemptStatus: c.attempt_status as string,
      startedAt: c.started_at as string,
      finalizedAt: (c.finalized_at as string | null) ?? null,
      assessmentId: c.assessment_id as string,
      assessmentTitle: c.assessment_title as string,
      candidateName: c.candidate_name as string,
      candidateRollNumber: (c.candidate_roll_number as string | null) ?? null,
    },
    status: raw.status as ReviewStatus,
    version: (raw.version as number | null) ?? null,
    outcome: (raw.outcome as ReviewOutcome | null) ?? null,
    startedBy: person(raw.started_by),
    startedAt: (raw.started_at as string | null) ?? null,
    completedBy: person(raw.completed_by),
    completedAt: (raw.completed_at as string | null) ?? null,
    canComplete: Boolean(raw.can_complete),
    notes: ((raw.notes as Raw[]) ?? []).map((n) => ({
      noteId: n.note_id as string,
      author: person(n.author) as Person,
      body: n.body as string,
      createdAt: n.created_at as string,
    })),
    decisions: ((raw.decisions as Raw[]) ?? []).map((d) => {
      const b = d.basis as Raw
      return {
        revision: d.revision as number,
        outcome: d.outcome as ReviewOutcome,
        outcomeDescription: d.outcome_description as string,
        rationale: d.rationale as string,
        decidedBy: person(d.decided_by) as Person,
        decidedAt: d.decided_at as string,
        basis: {
          policyVersion: b.policy_version as string,
          evidenceVersion: b.evidence_version as string,
          asOf: b.as_of as string,
          riskScore: b.risk_score as number,
          riskLevel: b.risk_level as RiskLevel,
          peakScore: b.peak_score as number,
          peakLevel: b.peak_level as RiskLevel,
          signalCount: b.signal_count as number,
          evidenceCount: b.evidence_count as number,
          episodeCount: b.episode_count as number,
        },
      }
    }),
    marks: ((raw.marks as Raw[]) ?? []).map((m) => ({
      evidenceId: m.evidence_id as string,
      mark: m.mark as EvidenceMark,
      markedBy: person(m.marked_by) as Person,
      markedAt: m.marked_at as string,
    })),
    history: ((raw.history as Raw[]) ?? []).map((h) => ({
      action: h.action as string,
      actor: person(h.actor) as Person,
      occurredAt: h.occurred_at as string,
      details: (h.details as Record<string, unknown>) ?? {},
    })),
    outcomeOptions: ((raw.outcome_options as Raw[]) ?? []).map((o) => ({
      outcome: o.outcome as ReviewOutcome,
      description: o.description as string,
    })),
    interpretation: raw.interpretation as string,
  }
}

export function toQueue(raw: Raw): ReviewQueue {
  const counts = (raw.counts as Raw) ?? {}
  return {
    counts: {
      UNREVIEWED: (counts.UNREVIEWED as number) ?? 0,
      IN_REVIEW: (counts.IN_REVIEW as number) ?? 0,
      REVIEWED: (counts.REVIEWED as number) ?? 0,
    },
    items: ((raw.items as Raw[]) ?? []).map((i) => ({
      attemptId: i.attempt_id as string,
      attemptNumber: i.attempt_number as number,
      attemptStatus: i.attempt_status as string,
      startedAt: i.started_at as string,
      finalizedAt: (i.finalized_at as string | null) ?? null,
      assessmentId: i.assessment_id as string,
      assessmentTitle: i.assessment_title as string,
      candidateName: i.candidate_name as string,
      candidateRollNumber: (i.candidate_roll_number as string | null) ?? null,
      riskLevel: i.risk_level as RiskLevel,
      riskScore: i.risk_score as number,
      peakLevel: i.peak_level as RiskLevel,
      reviewStatus: i.review_status as ReviewStatus,
      outcome: (i.outcome as ReviewOutcome | null) ?? null,
      reviewedBy: person(i.reviewed_by),
      reviewedAt: (i.reviewed_at as string | null) ?? null,
    })),
    nextCursor: (raw.next_cursor as string | null) ?? null,
    interpretation: raw.interpretation as string,
  }
}

/** `{evidence id: current mark}` for the evidence timeline. */
export function marksById(review: AttemptReview | null): Record<string, EvidenceMark> {
  return Object.fromEntries((review?.marks ?? []).map((m) => [m.evidenceId, m.mark]))
}
